# Generated by Django 3.2.9 on 2021-11-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tomeet_date_of_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('done_for_today', models.CharField(max_length=250)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
