# Generated by Django 3.2.9 on 2021-11-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
