# Generated by Django 3.2.9 on 2021-11-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_habits_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='user_name',
            new_name='habits_name',
        ),
    ]
